### PR TITLE
Use TDL column for Tclin, Tchem, Tbio in Drug Central ingest

### PR DESCRIPTION
**Pull request by justaddcoffee**
To address #198

### CODE REVIEW

**Comment by deepakunni3** [comment]
In the transformed nodes.tsv,

```
UniProtKB:P14867	GABRA1|GABRB2|GABRG2	biolink:Gene	Tclin|Tclin|Tclin
UniProtKB:P14867	GABRA1|GABRB2|GABRG2	biolink:Gene	Tclin|Tclin|Tclin
UniProtKB:P14867	GABRA1|GABRB3|GABRG2	biolink:Gene	Tclin|Tclin|Tclin
UniProtKB:P14867	GABRA1	biolink:Gene	Tclin
UniProtKB:P14867	GABRA1|GABRB2|GABRG2	biolink:Gene	Tclin|Tclin|Tclin
UniProtKB:P14867	GABRA1|GABRB2|GABRG3	biolink:Gene	Tclin|Tclin|Tclin
UniProtKB:P14867	GABRA1|GABRA2|GABRA3|GABRA4|GABRA5|GABRA6|GABRB1|GABRB2|GABRB3|GABRD|GABRG1|GABRG2|GABRG3	biolink:Gene	Tclin|Tclin|Tclin|Tclin|Tclin|Tclin|Tclin|Tclin|Tclin|Tclin|Tclin|Tclin|Tclin
UniProtKB:P14867	GABRA1|GABRA2|GABRA3|GABRA4|GABRA5|GABRA6|GABRB1|GABRB2|GABRB3|GABRD|GABRE|GABRG1|GABRG2|GABRG3|GABRP|GABRQ	biolink:Gene	Tclin|Tclin|Tclin|Tclin|Tclin|Tclin|Tclin|Tclin|Tclin|Tclin|Tclin|Tclin|Tclin|Tclin|Tclin|Tclin
```

The input data from DrugCentral provides drug to protein associations where the same drug is associated with more than one protein, but its all condensed into one line.

For example, this is a line from `drug.target.interaction.tsv`,
```
"acamprosate"   38      "GABA-A receptor alpha-1/beta-3/gamma-2"        "Ion channel"   "P14867|P18507|P28472"  "GABRA1|GABRB3|GABRG2"  "GBRA1_HUMAN|GBRB3_HUMAN|GBRG2_HUMAN"                                   "WOMBAT-PK"             1       "CHEMBL"                "https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL1201293"   "POSITIVE MODULATOR"    "Tclin|Tclin|Tclin"     "Homo sapiens"
```

When writing `nodes.tsv`, we need to split not just the `TARGET_NAME` column but also any other column that describes the target like `TARGET_CLASS`, `ACCESSION`, and TDL. 

Or we would end up with pipe separated values, which in some cases seem like repetition.

**Comment by justaddcoffee** [comment]
@deepakunni3 yes you are absolutely right. I will add this

**Comment by justaddcoffee** [comment]
Thanks very much @deepakunni3 - will fix this soon. 

nb. I believe this same issue exists for other ingests

**Comment by justaddcoffee** [comment]
Okay, @deepakunni3, duplicate nodes issue should be fixed (with unittest)

**Comment by justaddcoffee** [comment]
@deepakunni3 I think this might be ready to merge

**Pull request merged**
