### PR TITLE
Add script for merging data sources

### PR DESCRIPTION
**Pull request by deepakunni3**
This PR adds a script `merge_kg.py` that uses KGX to merge data sources, as defined in `sample-merge-config.yaml`.

This is just to demonstrate how we can use KGX to merge and it can serve as a starting point for the process of building a KG.

### CODE REVIEW

**Comment by justaddcoffee** [comment]
@deepakunni3 if you want, we could merge this, and I could make another PR that does what I describe above - I don't want to interrupt all this progress!

**Comment by deepakunni3** [comment]
@justaddcoffee Yes, I'll make the changes and push in a few mins 👍

**Comment by justaddcoffee** [comment]
+1 thanks @deepakunni3 !

**Comment by deepakunni3** [comment]
@justaddcoffee Ready for review again

**Comment by justaddcoffee** [comment]
Looks great thanks @deepakunni3 !

**Pull request merged**
