### PR TITLE
Ontology ingest

### PR DESCRIPTION
**Pull request by deepakunni3**
This PR adds an OntologyTransform that takes care of parsing Ontologies (as JSON format).
It uses KGX under the hood to do the transformation and export TSV.

This PR handles ingests for GO, HP and Mondo.

Addresses #97 and #72

### CODE REVIEW

**Comment by justaddcoffee** [comment]
Looks and works great! 

Could we get rid of my (inferior) HPO ingest with this PR? (I.e. get rid of 
`kg_covid_19/transform_utils/hpo/`, and the entries in `download.yaml` and `merge.yaml` and  `transform.py` for HPO)? 

We're adding a considerable number of nodes/edges here - I don't suppose there is an easy way to not ingest nodes/edges that don't involve just these ontologies and the links between them?: 
```
data/transformed/ontologies/go-plus_edges.tsv:181978
data/transformed/ontologies/go-plus_nodes.tsv:156062
data/transformed/ontologies/hp_edges.tsv:18950
data/transformed/ontologies/hp_nodes.tsv:30203
data/transformed/ontologies/mondo_edges.tsv:117410
data/transformed/ontologies/mondo_nodes.tsv:121350
```

**Comment by matentzn** [comment]
Will have a proposal for that. Bear with me.

**Comment by justaddcoffee** [comment]
> Will have a proposal for that. Bear with me.

Thanks Nico!

**Comment by deepakunni3** [comment]
Sure! Changes incoming...

**Comment by justaddcoffee** [comment]
Discussed with @deepakunni3 - plan is to wait on the merge of this ontology PR until we produce a simple v0.1 version of the graph

**Pull request merged**
