### PR TITLE
Update scibite cord ingest

### PR DESCRIPTION
**Pull request by deepakunni3**
This PR bumps up the version of SciBite CORD-19 datasets in `download.yaml`

@justaddcoffee I added back the entity co-occurrence dataset but its not being transformed at the moment. If we transform that dataset, we end up with ~23 million nodes and ~23 million edges just from this ingest. 

Maybe we can enable the transformation later on, if needed.

### CODE REVIEW

**Comment by justaddcoffee** [comment]
> This PR bumps up the version of SciBite CORD-19 datasets in `download.yaml`
> 
> @justaddcoffee I added back the entity co-occurrence dataset but its not being transformed at the moment. If we transform that dataset, we end up with ~23 million nodes and ~23 million edges just from this ingest.
> 
> Maybe we can enable the transformation later on, if needed.

Excellent, thanks @deepakunni3. 

If we feel like others might want the co-occurrence data (or we want to experiment with including a subset of these co-occurrence data for our ML experiments), we could enable the transform of the co-occurrence data, but disable the merge for now.

**Comment by deepakunni3** [comment]
@justaddcoffee Okay, I'll add a provision for that then. Thanks 👍

**Comment by deepakunni3** [comment]
This PR now adds an hour to the build.

**Comment by justaddcoffee** [comment]
> This PR now adds an hour to the build.

Okay, thanks for checking that. What do you want to do? I say we merge anyway, because with the RDF conversion stage (~8 hours) and blazegraph journal stage (1 day) the build time is now almost a day and a half. We can iterate to make this quicker later. What do you think?

**Comment by justaddcoffee** [comment]
> > This PR now adds an hour to the build.
> 
> Okay, thanks for checking that. What do you want to do? I say we merge anyway, because with the RDF conversion stage (~8 hours) and blazegraph journal stage (1 day) the build time is now almost a day and a half. We can iterate to make this quicker later (see https://github.com/Knowledge-Graph-Hub/kg-covid-19/issues/152). What do you think?

**Comment by deepakunni3** [comment]
Yes, good call. We can disable it later if its slowing things down too much

**Comment by justaddcoffee** [comment]
+1

**Pull request merged**
