### PR TITLE
Drug central ingest

### PR DESCRIPTION
**Pull request by justaddcoffee**
- Added ingest for Drug Central to address #5 
- Added a class (`transform.py`) and a few utilities to dry out future transforms

### CODE REVIEW

**Comment by callahantiff** [comment]
@justaddcoffee - I have been linking the issues that the PRs (fully or even partially address). Are you OK with that?

**Comment by justaddcoffee** [comment]
> @justaddcoffee - I have been linking the issues that the PRs (fully or even partially address). Are you OK with that?

yes, please do - I should've done that myself

**Comment by justaddcoffee** [comment]
@callahantiff If this PR looks okay, I'll merge

**Comment by callahantiff** [comment]
> @callahantiff If this PR looks okay, I'll merge

Yes, please looks great. Sorry, I should have merged it. Will do that immediately in future reviews.

**Comment by justaddcoffee** [comment]
thanks @callahantiff

**Pull request merged**
