### PR TITLE
Add support for compressed exports at merge step

### PR DESCRIPTION
**Pull request by deepakunni3**

### CODE REVIEW

**Comment by deepakunni3** [comment]
This, along side latest changes on deepakunni3/kgx repo should get our pipeline going without the long merge step.

**Comment by justaddcoffee** [comment]
Looks good, thanks Deepak!

I think we'll need to remove [this line](https://github.com/Knowledge-Graph-Hub/kg-covid-19/blob/6fb5109f2a6d27e31790df7790ba3684e7854f89/Jenkinsfile#L99) from the Jenkinsfile too

**Comment by justaddcoffee** [comment]
> I think we'll need to remove this line from the Jenkinsfile too

took the liberty, hope that's okay

**Comment by deepakunni3** [comment]
@justaddcoffee Thanks for merging this in 👍

**Comment by deepakunni3** [comment]
Okay.. good catch on removing the extra `pigz` line.
But we should be removing both the pigz lines since the merge step will generate `merged-kg.tar.gz` and `merged-kg.nt.gz` by itself.

**Comment by justaddcoffee** [comment]
Okay, no problem - made a quick PR here:
https://github.com/Knowledge-Graph-Hub/kg-covid-19/pull/311

**Pull request merged**
