### PR TITLE
ChEMBL ingest for SARS-CoV-2 subset

### PR DESCRIPTION
**Pull request by deepakunni3**
ChEMBL ingest for SARS-CoV-2 subset.

The nature of the subset is described here: http://chembl.blogspot.com/2020/05/chembl27-sars-cov-2-release.html

The code basically queries different ChEMBL resources and fetches the relevant data.
We can expand on this with additional canned queries that be used to fetch more defined subsets.

### CODE REVIEW

**Comment by deepakunni3** [comment]
@justaddcoffee This is ready for review and feedback.

**Comment by justaddcoffee** [comment]
This is great @deepakunni3 ! Will review soon

**Comment by justaddcoffee** [comment]
This looks good to me. 

Some observations:
- this PR introduces a network requirement during the transform step (this is more of an observation than a criticism - if we see failures during the transform step we should consider network issues. Also we will no longer have the full complement of input data necessary for all transforms.)

- If possible, could we sort the nodes and edges TSV such that the required fields are first? I.e. nodes.tsv:
`id   category`
and edges.tsv:
`subject    edge_label     object    relation    provided_by`
Not a big deal if you'd rather not.

**Comment by deepakunni3** [comment]
@justaddcoffee I have added provisions to persist the results fetched from the API to the raw folder. This should allow for the data to be part of our build archives.

**Comment by justaddcoffee** [comment]
great @deepakunni3 !

**Comment by justaddcoffee** [comment]
running Jenkins on this now, we'll have ChEMBL by tomorrow!

**Comment by deepakunni3** [comment]
🕺

**Pull request merged**
