### PR TITLE
First pass at go-cam ingest

### PR DESCRIPTION
**Pull request by justaddcoffee**
WIP - this ingests go-cam models produced by @callahantiff and Bill, to address #153 

@deepakunni3, please feel free to close this PR if you'd rather do it some other way. 

Currently doesn't produce any useful edges

### CODE REVIEW

**Comment by deepakunni3** [comment]
Thanks! I'll push to this branch once I finish tweaking KGX.

**Comment by justaddcoffee** [comment]
@deepakunni3 ping! Curious where we are on this KGX tweaking to make it more GO-CAM RDF friendly (no rush)

**Comment by deepakunni3** [comment]
@justaddcoffee The tests seem to be failing for `tests/test_download_from_yaml.py`

Unclear what is happening here. Thoughts?

**Comment by justaddcoffee** [comment]
> @justaddcoffee The tests seem to be failing for tests/test_download_from_yaml.py
> Unclear what is happening here. Thoughts?

Yeah, these tests are brittle, I need to refactor them. I removed them in `master` - just cherry-picked a commit that removes them.

**Comment by justaddcoffee** [comment]
Seems to work on my end:
```
python run.py transform -s GocamTransform
[SNIP]
[rdf_transformer.py][               parse] INFO: Done parsing data/raw/lifted-go-cams-20200619.xml
[transformer.py][              report] INFO: Total nodes in graph: 3681
[transformer.py][              report] INFO: Total edges in graph: 3724
```

@deepakunni3 do you want me to do a Jenkins run on this? Or merge now? Up to you

**Comment by deepakunni3** [comment]
@justaddcoffee This is ready to merge if we are happy with the nodes and edges TSV that is being generated.

**Note:** Our NT export will be a bit unstable if we run the pipeline now. I am making a PR to fix that. So a proper pipeline run will have to wait until we get that PR merged as well.

**Comment by justaddcoffee** [comment]
> Note: Our NT export will be a bit unstable if we run the pipeline now. I am making a PR to fix that. So a proper pipeline run will have to wait until we get that PR merged as well.

Okay how about if we merge this, and you can ping me when the PR to fix the NR export issue is merged and I'll run the Jenkins pipeline

**Comment by deepakunni3** [comment]
Sounds good!

**Pull request merged**
