### PR TITLE
Update readme and setup

### PR DESCRIPTION
**Pull request by justaddcoffee**
- added a few deps to `setup.py`
- added an item in `README.rst` to run `pip install -r requirements.txt` (to ensure KGX is installed)

### CODE REVIEW

**Comment by deepakunni3** [comment]
@justaddcoffee Why not have KGX be part of setup.py?

**Comment by justaddcoffee** [comment]
> @justaddcoffee Why not have KGX be part of setup.py?
> That way we can just get rid of requirements.txt and have all dependencies tracked in setup.py

I'd be in favor of that, but I think @LucaCappelletti94 encountered some issue when we tried that

**Comment by deepakunni3** [comment]
Yes, now I remember. Okay, we can remove `requirements.txt` later

**Comment by justaddcoffee** [comment]
thanks @deepakunni3 !

**Comment by LucaCappelletti94** [comment]
Hi @deepakunni3! I thought that KGX was not available [as a python package on pypi](https://pypi.org/search/?q=kgx) hence it required a direct installation from the repository, which we could not manage to integrate with the setup.py. Is there a python package? Or did you manage to integrate the repository? Or there's a third way?

I would love to learn how to do it! Thanks!

**Pull request merged**
